### ISSUE TITLE
[feat] More output on the build/deploy step

### ISSUE THREAD

**Issue by markusthoemmes** [boson-project/faas#189]
**Describe the solution you'd like**
My `kn faas build` command was literally

```console
$ kn faas build
Building image: docker.io/markusthoemmes/node:latest
```

A spinner would've been neat as it has been sitting there for a while. A `Success` message would also be nice on... well... success.

**Comment by zroubalik** [comment]
Discussed this with @lkingland, Implementing the spinner properly (so it is not eating the output) may take some time. So I'll proceed with printing some basic info messages, since we are under such a tight deadline.

And we will revisit the Spinner properly for all the commands as a post Dev Preview task.
